# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -DOMPVER2
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -DOMPVER2 -DOMPVER3

CC=${LLVM_PATH}/bin/clang
CFLAGS =  -O1 -lm -fopenmp
LDFLAGS = -O0 -lm -L${LLVM_PATH}/lib -Wl,--rpath=${LLVM_PATH}/lib -lomp
CPP = /usr/bin/cpp
LIBS = 
